# Generated by Django 3.2.16 on 2023-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
