# Generated by Django 3.2.16 on 2023-01-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='location',
        ),
        migrations.AddField(
            model_name='meetup',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetups.location'),
        ),
    ]
