# Generated by Django 3.2.16 on 2023-01-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20230115_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
