# Generated by Django 3.2.16 on 2023-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_meetup_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
