# Generated by Django 3.2.16 on 2023-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_participants_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(related_name='meetup', to='meetups.Participants'),
        ),
    ]
